stages:          # 파이프라인 단계 정의
  - build
  - deploy

variables:
  DOCKER_IMAGE_NAME: byaht/tmap-spring:0.1.2

build-job:       # 빌드 단계
  stage: build
  image: gradle:jdk17
  script:
    - echo "Build application..."
    - gradle bootJar
    - docker build -t $DOCKER_IMAGE_NAME .
    - echo "Application successfully build..."
deploy-job:      # 배포 단계
  stage: deploy
  only:
    - main
  script:
    - echo "Deploying application..."
    - docker push $DOCKER_IMAGE_NAME
    - echo "Application successfully deployed."
