stages:          # 파이프라인 단계 정의
  - build
  - deploy

variables:
  DOCKER_IMAGE_NAME: byaht/tmap-spring:0.1.2

build-job:       # 빌드 단계
  stage: build
  image: gradle:jdk17
  script:
    - echo "Build application..."
    - gradle bootJar
    - docker build -t byaht/tmap-spring:0.1.2 .
    - echo "Application successfully build..."
deploy-job:      # 배포 단계
  stage: deploy
  only:
    - main
  script:
    - echo "Deploying application..."
    - docker push byaht/tmap-spring:0.1.2
    - echo "Application successfully deployed."
